### ISSUE TITLE
BUG: Rust code action and nvim-cmp report error with the latest neovim nightly build

### ISSUE THREAD

**Issue by Avimitin** [Avimitin/nvim#11]
Tracking this issue on https://github.com/simrat39/rust-tools.nvim/pull/128 and https://github.com/hrsh7th/nvim-cmp/issues/726#issuecomment-1012213386.

**Comment by Avimitin** [comment]
LSP format is also down.

**Comment by ocfox** [comment]
Is there a temporary solution？

**Comment by Avimitin** [comment]
> Is there a temporary solution？

Clone the neovim repository and use `git checkout stable` to build the 0.6.1 version. 

---

If you are Arch Linux user, you can download the PKGBUILD manually by command `yay -G neovim-git` and add a prepare function like this:

```diff
+prepare() {
+  cd "${pkgname}"
+  git checkout stable
+}
+
```
then run command `makepkg -si` to build and install.

**Comment by ocfox** [comment]
Thank you. It's working well.

**Comment by Avimitin** [comment]
Rust-tools had fixed this: https://github.com/simrat39/rust-tools.nvim/commit/10bb39aa1630d25648a183170d130b19d213a0a4.

**Comment by Avimitin** [comment]
Closing this as it has been fixed. But I don't test it by myself yet.
