### ISSUE TITLE
how to load nvim-lsp-installer plugin automatically when open  ts / tsx files?

### ISSUE THREAD

**Issue by ilaipi** [Avimitin/nvim#23]
I have install eslint & tsserver , but when open tsx files, I need to run `PackerLoad nvim-lsp-installer` to active lsp server

**Comment by Avimitin** [comment]
You can add `typescript` into this array: https://github.com/Avimitin/nvim/blob/master/lua/plugins/load.lua#L486. To check current file type you can use command `:echo &filetype` or `:lua print(vim.b.filetype)`.

I don't write frontend much so I don't add it as default.

**Comment by ilaipi** [comment]
Thanks, worked after add  `typescript and typescriptreact`  to ft config
