### ISSUE TITLE
file tree resize on open a file

### ISSUE THREAD

**Issue by ilaipi** [Avimitin/nvim#24]
`;t` open file tree

`ctrl + shift + Left / Right` resize file tree window

select a file, press enter to open, and then file tree resize to default size.

It is fixed before several commits, how to revert this?

**Comment by Avimitin** [comment]
Oh, I don't know this behavior. I will check this later.

**Comment by Avimitin** [comment]
I've set auto_resize to false. But it still resize automatically. I think this is a bug from nvim-tree.lua. I've report it in https://github.com/kyazdani42/nvim-tree.lua/issues/1034.

**Comment by Avimitin** [comment]
It's been fixed.
