### ISSUE TITLE
coding error

### ISSUE THREAD

**Issue by ilaipi** [Avimitin/nvim#25]
![image](https://user-images.githubusercontent.com/1689135/156091138-45095044-4fab-4ec2-a9fc-a5d83a296cac.png)

after seconds:

![image](https://user-images.githubusercontent.com/1689135/156091186-01e8c290-a696-4b13-a70a-0ba24dfbd2e3.png)

**Comment by Avimitin** [comment]
I got this error too. This is not related to the neovim configuration. This is related to the terminal. Terminal can not draw nerd font icon correctly. Some nerd font icon takes 4 to 6 character width. And it mess up the neovim. My suggestion is to use Nerd Font Mono font, this can help a bit. If it keeps appearing, you can choose to remove the nerd fond icon in lspconfig_cfg.lua file.

![image](https://user-images.githubusercontent.com/30021675/156091548-ba55140b-171b-4227-b5a3-4726cbac061a.png)

Replace this icon with normal text or just close it can help.

**Comment by Avimitin** [comment]
There is also another alternative way. You can close virtual text for specific language:

```lua
   -- replace rust_analyzer with your lsp server
   require('lspconfig').rust_analyzer.setup {
     handlers = {
       ["textDocument/publishDiagnostics"] = vim.lsp.with(
         vim.lsp.diagnostic.on_publish_diagnostics, {
           -- Disable virtual_text
           virtual_text = false
         }
       ),
     }
   }
```

**Comment by Avimitin** [comment]
See if this commit can fix this issue: 11c01a99d60c796883b7a5edbee9e5a714718847

**Comment by ilaipi** [comment]
I have merge this and will watch on it. Thanks!

**Comment by Avimitin** [comment]
Besides, I recommend you run command `:TSInstall typescript`. You will be surprised.

**Comment by ilaipi** [comment]
> Besides, I recommend you run command `:TSInstall typescript`. You will be surprised.

Thanks, it seems can show suggestions after installed.

**Comment by Avimitin** [comment]
Do you have any problem this days? I am preparing to release the final 4.0.0 version. If you didn't met any bugs, please tell me.

**Comment by ilaipi** [comment]
I didn't met such problem since this fix. Closed, Thanks!
