### ISSUE TITLE
file tree resize when left or enter tree window

### ISSUE THREAD

**Issue by ilaipi** [Avimitin/nvim#26]
left:
![image](https://user-images.githubusercontent.com/1689135/156953401-c27be3cb-d18e-415e-a47f-8c1372f7ede7.png)

enter:

![image](https://user-images.githubusercontent.com/1689135/156953461-5f6e3c92-7719-4149-8791-2d81df261716.png)

I met this after sync your latest commit of yestoday.

**Comment by Avimitin** [comment]
This is caused by [focus.nvim](https://github.com/beauwilliams/focus.nvim) plugin. It is not a bug.

**Comment by ilaipi** [comment]
Oh, try to understand and accept it, thanks.

**Comment by Avimitin** [comment]
You can remove this plugin if you feel weird about it.

**Comment by Avimitin** [comment]
I've found a option to close this, you can try this commit: 97855b6f36b5530bad7d45dea1399986a3521a93

**Comment by ilaipi** [comment]
It seems ok

**Comment by ilaipi** [comment]
![origin_img_v2_386b6b50-1066-4e03-9854-c1f5385d9bag](https://user-images.githubusercontent.com/1689135/156960574-6e9d4207-c90a-47e4-9072-43c9bf26f398.png)

I install this on my mac, met this error. No errors on wsl2 ubuntu

**Comment by Avimitin** [comment]
> ![origin_img_v2_386b6b50-1066-4e03-9854-c1f5385d9bag](https://user-images.githubusercontent.com/1689135/156960574-6e9d4207-c90a-47e4-9072-43c9bf26f398.png)
> 
> I install this on my mac, met this error. No errors on wsl2 ubuntu

This might belong to another talking thread, I post this to the new issue #27.
