### ISSUE TITLE
Fail to install on Mac OS

### ISSUE THREAD

**Issue by Avimitin** [Avimitin/nvim#27]
![origin_img_v2_386b6b50-1066-4e03-9854-c1f5385d9bag](https://user-images.githubusercontent.com/1689135/156960574-6e9d4207-c90a-47e4-9072-43c9bf26f398.png)

> I install this on my mac, met this error. No errors on wsl2 ubuntu

_Originally posted by @ilaipi in https://github.com/Avimitin/nvim/issues/26#issuecomment-1060139468_

**Comment by Avimitin** [comment]
I don't have macbook or other stuff that can run mac os. So this might be hard to figure out what happen. @ilaipi

**Comment by ilaipi** [comment]
Maybe it's because the network, after I retry `PackerInstall` several times, the plugins are all installed succesfully.

**Comment by Avimitin** [comment]
> Maybe it's because the network, after I retry `PackerInstall` several times, the plugins are all installed succesfully.

Can you remove all the plugins and cache and then run a fresh installation?

**Comment by ilaipi** [comment]
I run a fresh installation at the begining by run :
```
# plugins directory
rm -rf ~/.local/share/nvim

# neovim cache file
rm -r ~/.cache/nvim

# neovim plugins load sequence
rm -r ~/.config/nvim/plugin
```
(from the installation guide)

And I just try one more time , the same error.

**Comment by Avimitin** [comment]
So this might not be a network issue. I will try to figure it out. (See if I can borrow a MacBook from someone else.)

**Comment by Avimitin** [comment]
I've asked some of my friends, and they said they got no error during the installation. So you might need to find out the issue yourself.

**Comment by Avimitin** [comment]
And yes, it is related to the network. I've read the source code from [jobs.lua](https://github.com/wbthomason/packer.nvim/blob/master/lua/packer/jobs.lua#L86) file, and it occurs when killing the process.

**Comment by ilaipi** [comment]
Ok, let's close this, thanks!
