### ISSUE TITLE
which plugin cause this error?

### ISSUE THREAD

**Issue by ilaipi** [Avimitin/nvim#28]
![image](https://user-images.githubusercontent.com/1689135/157356305-1fec5683-2589-4676-b950-85ae2aa00c44.png)

I use ts to develop, and my project is like this:

```
- workspace
  - project A
  - project B
```

I enter `workspace` and run `nvim` to open editor,  my `tsconfig.json` is in every project dir.

**Comment by Avimitin** [comment]
Do you have minimum project for me to test?

**Comment by Avimitin** [comment]
I am confusing, what is your problem?

* Your lsp can't find out tsconfig?
* Your workspace is polluted by tsconfig?

**Comment by ilaipi** [comment]
I think this is caused by the `rooter`, but can't figure out the problem.

if I run `nvim` in `project A` dir, then no error reported.

**Comment by Avimitin** [comment]
Rooter will change root path by finding the root pattern. Like it will try to cd in the directory with .git, or directory with go.mod...etc. I have a question that is, how the tsconfig work? Should it be as the root directory pattern?

**Comment by ilaipi** [comment]
> Should it be as the root directory pattern

Yes, it should be.

![image](https://user-images.githubusercontent.com/1689135/157358334-7fdc208d-5720-4c0e-a12b-690378f632c1.png)

I tried to add it to the patterns, but seems no effect

**Comment by ilaipi** [comment]
`E492: Not an editor command: LuaCacheClean`

**Comment by Avimitin** [comment]
Sorry, it is LuaCacheClear

**Comment by ilaipi** [comment]
still have this error

**Comment by Avimitin** [comment]
Can you give me a minimum project to test this?

**Comment by ilaipi** [comment]
do u have node installed ?

**Comment by Avimitin** [comment]
Yes

**Comment by ilaipi** [comment]
Oh, can u use nestjs to `new` a empty project?

https://docs.nestjs.com/cli/usages

```
mkdir test-ts
cd test-ts
nest new foo

```
and then `nvim`,

**Comment by Avimitin** [comment]
Can you run `tree` command in your workspace directory? I want to know your workspace file structure.

**Comment by ilaipi** [comment]
```
> tree
.
├── bar
│   ├── README.md
│   ├── nest-cli.json
│   ├── package.json
│   ├── src
│   │   ├── app.controller.spec.ts
│   │   ├── app.controller.ts
│   │   ├── app.module.ts
│   │   ├── app.service.ts
│   │   └── main.ts
│   ├── test
│   │   ├── app.e2e-spec.ts
│   │   └── jest-e2e.json
│   ├── tsconfig.build.json
│   └── tsconfig.json
└── foo
    ├── README.md
    ├── nest-cli.json
    ├── package.json
    ├── src
    │   ├── app.controller.spec.ts
    │   ├── app.controller.ts
    │   ├── app.module.ts
    │   ├── app.service.ts
    │   └── main.ts
    ├── test
    │   ├── app.e2e-spec.ts
    │   └── jest-e2e.json
    ├── tsconfig.build.json
    └── tsconfig.json
```

**Comment by Avimitin** [comment]
I can't reproduce your error. Everything is working well in my environment. I am using TSserver as LSP, and no error reported.

**Comment by ilaipi** [comment]
![image](https://user-images.githubusercontent.com/1689135/157401796-7a02c0fb-a187-4bf3-b787-d60582c743ad.png)

I both install `tsserver` and `eslint` lsp server, and after I uninstall `eslint` lsp server, the error fixed.

**Comment by Avimitin** [comment]
The rooter issue is fixed. But I don't think this error is related to the rooter. It might related duplicate lsp server. I don't met this error when I am using eslint only.

**Comment by ilaipi** [comment]
ok, thanks very much~
