### ISSUE TITLE
command line mode can complete by tab after <leader>f

### ISSUE THREAD

**Issue by ilaipi** [Avimitin/nvim#31]
steps:
- nvim, enter editor
- input ':' , enter `Te`, press `Tab`, complete `Texplore`
- < leader > f, and then press `esc`
- input ':', enter `Te`, nothing complete. even `Pa` no response.

Are u ok?

**Comment by Avimitin** [comment]
I can't reproduce. There is no keybinding for `<leader>f`. And even represent the steps, I can still get completion done. Do you map anything to the leader key?

**Comment by ilaipi** [comment]
[nvim-telescope/telescope.nvim](https://github.com/nvim-telescope/telescope.nvim)

maybe no map for `<leader>f`, but accord to this plugin, there is default key map: `<leader>ff`, 

but actually in this config, `<leader>f` has the same effect with `<leader>ff`.

I didn't edit the `<leader>` key, the same with this config, is `;`

**Comment by ilaipi** [comment]
how do u search from current project or a specific directory ?

**Comment by Avimitin** [comment]
what do you mean?

**Comment by ilaipi** [comment]
Oh... 

- I have test on mac and Ubuntu, `<leader>f`(`;f`) is map to `nnoremap <leader>ff <cmd>Telescope find_files<cr>`
- Search is a very useful skill when we code, so how do you search a word in nvim within current project or a specific directory? I  think [nvim-telescope/telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) is for search.

**Comment by Avimitin** [comment]
There is no default keymappings for telescope. I only map two of them. One is the `;f` to search file, another is `<space>tg` to grep keyword. You can see the definition in this file: https://github.com/Avimitin/nvim/blob/master/lua/mappings/other.lua#L20.

And by default there is no `<leader>f` keybinding. So this is a weird bug. You might want to run `:PackerSync` to upgrade plugins. If the error is still performing, try open issue here https://github.com/hrsh7th/cmp-cmdline/issues.

**Comment by ilaipi** [comment]
Okkkk... My mistake, I have always think `<leader>` is `;`

And, after `:PackerSync`, the problem is fixed.

Thank you very much !!!

**Comment by Avimitin** [comment]
Leader key definition is here: https://github.com/Avimitin/nvim/blob/master/lua/mappings/init.lua#L6, which is space. And `;` is another definition.
