### ISSUE TITLE
is there any way to see the full error info?

### ISSUE THREAD

**Issue by ilaipi** [Avimitin/nvim#32]
![image](https://user-images.githubusercontent.com/1689135/160972252-6bac2863-d10d-48b6-aec9-e107799080fa.png)

sorry to report it, but sometimes it really troubled me.

this is a simple error just for example. Sometimes it's a long error, no newline, can't see fully.

<img width="1140" alt="2d1e705b49402e402c6ff960d0f4fdd" src="https://user-images.githubusercontent.com/1689135/160972533-6ed3e0db-9a0c-42ca-b95e-90140c09ea1a.png">

and some others like this , error in commond line

**Comment by Avimitin** [comment]
Use `:messages` or `:Notifications`. For LSP error, move cursor to the code and press key `go` to open diagnostic panel.

**Comment by ilaipi** [comment]
very useful, thank you very much!
