### ISSUE TITLE
ctrl + y in visual mode not worked

### ISSUE THREAD

**Issue by ilaipi** [Avimitin/nvim#33]
I have always occur this problem.

in visual mode, select some text, press `ctrl + y`, nothing response. sometimes it's ok.

Windows, wsl 2, use Windows Terminal.

**Comment by Avimitin** [comment]
Run `:checkhealth` to see if your clipboard is working well.

**Comment by ilaipi** [comment]
![image](https://user-images.githubusercontent.com/1689135/162875508-59bac733-b308-4f71-bd61-85342c9f7cba.png)

sometimes it's ok, sometimes not.

I will checkhealth when it's not ok next time.

**Comment by Avimitin** [comment]
And it may be wsl issue. Maybe, xclip fail to transfer pasteboard contents to the Windows host.

**Comment by ilaipi** [comment]
Oh, met this error just now, and `:checkhealth ` print the same info with above screenshot.

**Comment by Avimitin** [comment]
> And it may be wsl issue. Maybe, xclip fail to transfer pasteboard contents to the Windows host.

Might relate to this.

**Comment by Avimitin** [comment]
Closed as the configuration can do nothing about it.
