### ISSUE TITLE
Issues related with installation

### ISSUE THREAD

**Issue by Ahacad** [Avimitin/nvim#4]
Hi, I'm completely new to lua for nvim, and met some issues when trying to install your configurations. Though I've managed to solve them, I guess you might add some guides in the README. I guess one needs to manually call `:PackerInstall` when first opening? Not sure if the installation starts automatically by the code, but on my machine it didn't.

**Comment by Avimitin** [comment]
Do you meet any error when you open the neovim? You can use the command `:messages` to see the log. 

Also please check if the packer plugin is already installed. It should start the installation for the first time automatically by default. The logic is to see if the packer.nvim is existed in path `~/.local/share/nvim/site/pack/packer/opt/packer.nvim`.

I recommend you to delete the whole `~/.local/share/nvim` directory for a fresh installation.

Check the code here: https://github.com/Avimitin/nvim/blob/master/lua/utils.lua#L50

**Comment by Ahacad** [comment]
Thank you, I've also met the problem related to `Rooter` which was solved in the latest commit e43531411bf8cbec22c48bc21782a64155afeac0. Deleting the whole `~/.local/share/nvim` was a good practice :+1:. I've tried to reinstall, there were still some warnings, but the packer git clone panel showed up and other things went soomthly. After installation and restarting the warnings are gone and everything is good. I think the warnings are related to the issues when plugins were not fully installed. I've put some of them below for your reference.

```
Error in packer_compiled: /home/ahacad/.config/nvim/plugin/packer_compiled.lua:643: Vim(source):E484: Can't open 
file /home/ahacad/.local/share/nvim/site/pack/packer/opt/vim-go/ftdetect/gofiletype.vim
```

```
Error in packer_compiled: /home/ahacad/.config/nvim/plugin/packer_compiled.lua:643: Vim(source):E484: Can't open 
file /home/ahacad/.local/share/nvim/site/pack/packer/opt/nvim-treesitter/ftdetect/elixir.vim
Please check your config for correctness
```

**Comment by Avimitin** [comment]
Rooter error has been fixed: https://github.com/Avimitin/nvim/commit/e43531411bf8cbec22c48bc21782a64155afeac0

**Comment by Avimitin** [comment]
Seems like the tree-sitter plugin are partially installed. I will mention the clean up step in readme.

**Comment by Avimitin** [comment]
> Seems like the tree-sitter plugin are partially installed. I will mention the clean up step in readme.

Fixed in: https://github.com/Avimitin/nvim/commit/14cfdcf2cf814998c5e69f2fe6c58b98ce84131a
