### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by Avimitin** [Avimitin/nvim#41]
Unit test must be done. It is fucked to use docker to test the editor.

**Comment by towry** [comment]
```
nstalling packer to /Users/towry/.local/share/nvim/site/pack/packer/opt/packer.nvim
Error executing vim.schedule lua callback: /Users/towry/.config/nvim/lua/plugins/enhance/keymap.lua:146: module 'hydra' not found:
```

I was trying to reproduce an issue with fresh new repo, and encounter this error.

**Comment by Avimitin** [comment]
> ```
> nstalling packer to /Users/towry/.local/share/nvim/site/pack/packer/opt/packer.nvim
> Error executing vim.schedule lua callback: /Users/towry/.config/nvim/lua/plugins/enhance/keymap.lua:146: module 'hydra' not found:
> ```
> 
> I was trying to reproduce another issue with fresh new repo, and encounter this error.

Please open a new issue.
