### ISSUE TITLE
questions after upgrade to 0.7

### ISSUE THREAD

**Issue by ilaipi** [Avimitin/nvim#42]
hello~

after upgrade to 0.7, I have 2 questions,

- how to redo last operation? before  is `.`, now `.` is mapped to go to next buffer
- how to disable the "auto double quotation marks" for the key in json file?
![image](https://user-images.githubusercontent.com/1689135/167250503-90613a01-3796-43d2-bf02-1cf05dc4e5d0.png)
(the line under cursor auto add '"' to key "@nestjs/config")

**Comment by Avimitin** [comment]
- Q1: How to redo last operation?
	This was perform by the vim-repeat plugin. But I removed it since I don't need it. I use vim macro for repeat operation. You can add this plugin back.

- Q2: How to disable auto quote?
	In json, all keys must be enclosed in double quotes. So there is no reason to remove double quotes. Maybe you are talking about the conceal text? Neovim will automatically hide the double quotes when the cursor is not cover that line. You can close the conceal feature in `lua/core/options.lua`, set the `opt.conceallevel` to `0`.

**Comment by ilaipi** [comment]
Thanks~

About A1:    
After I change the mapping for next buffer from `.` to `;n`, `.` back to be repeat last operation, no need for `vim-repeat`.


About A2:
very nice soluation~
