### ISSUE TITLE
没有自动 compile。

### ISSUE THREAD

**Issue by towry** [Avimitin/nvim#44]
参考文档 clone 到本地，然后启动 nvim，packer 自动运行了。

但是关闭再打开后，发现一些命令 `:NvimTreeToggle` 都不存在。折腾了一会，发现 Packer 没有 compile，我手动运行了 `:PackerComile` 后，主题色变了，命令也有了，才知道是安装成功了。

可能是网络问题，这几一个一直是 fetching 状态。

![截屏2022-06-10 09 36 55](https://user-images.githubusercontent.com/8279858/172972779-7e1d8fdf-b118-4075-a2ee-918398a75e7c.png)

**Comment by Avimitin** [comment]
我去研究一下。一般来说 sync 就会自动 compile 的，不知道是不是 packer 改变了行为。

**Comment by Avimitin** [comment]
诶这个会卡住吗，我自己用没卡住过。那我把这个加上把

**Comment by towry** [comment]
补充：

之前nvim目录里没有手动创建 `plugin` 目录。

**Comment by Avimitin** [comment]
把 ~/.config/nvim, ~/.cache/nvim, ~/.local/share/nvim 给删除了，然后重新再跑一次试试。
