### ISSUE TITLE
PackCompile 会导致重复的命令提示

### ISSUE THREAD

**Issue by towry** [Avimitin/nvim#46]
https://user-images.githubusercontent.com/8279858/173261629-6ce8d6cc-63e9-4346-8f77-ce4082581cb7.mov

看录屏，可能不是这个配置的问题，不知道你那里能不能复现。

**Comment by towry** [comment]
@Avimitin 麻烦再问下，就是在 nvimtree中，按 `shift + i` 即 `I` 应该是要 切换显示 被 ignore 的文件的，但是我这里的表现确实，打开关闭节点，你那里有这个问题吗？

配置：https://github.com/Avimitin/nvim/blob/9cdaf4523004b292fee6241f9168faac181b3665/lua/plugins/config/nvimtree_cfg.lua#L120

`shift + h` 是工作正常的。

**Comment by Avimitin** [comment]
修好了 https://github.com/Avimitin/nvim/commit/5bfb530bc3d1d28dd49724c25b6dff56dd6a4dac。你更新一下配置文件就行。

**Comment by towry** [comment]
@Avimitin 我现在想修改配置，将 `<C-i>` 映射成 `<ESC>`，即在 insert 模式，同时按下 `CTRL+i` 退出 insert 模式。但是发现加了无效（换成`<C-y>`是OK的），现在的表现是 类似 tab 键。

我使用 `:help index` 查看到如下内容：

![截屏2022-06-13 13 53 40](https://user-images.githubusercontent.com/8279858/173288857-aeeeac4b-5162-483b-928e-368d5ae82061.png)

insert模式下，`<C-i>` 和 `<Tab>` 效果一样。

想知道这是配置里影响的还是这个无法修改？

**Comment by Avimitin** [comment]
我没有修改 <C-i> 这个按键，我试了一下直接设置 `inoremap <C-i> <ESC>` 就生效了，你的配置是怎么写的呢？

**Comment by Avimitin** [comment]
如果你是用的我的配置文件的话，可以在 `lua/mappings/init.lua` 文件里加上一句：`map("i", "<C-i>", "<ESC>")`

**Comment by towry** [comment]
https://github.com/towry/dotfiles/blob/af3cbfa0f1c0d991486507978025fde4c6ff161e/link/.config/nvim/lua/mappings/init.lua#L58

用的是你的配置。

**Comment by Avimitin** [comment]
> [towry/dotfiles@`af3cbfa`/link/.config/nvim/lua/mappings/init.lua#L58](https://github.com/towry/dotfiles/blob/af3cbfa0f1c0d991486507978025fde4c6ff161e/link/.config/nvim/lua/mappings/init.lua#L58)
> 
> 用的是你的配置。

这样配置了还是用不了吗？

**Comment by towry** [comment]
> 我没有修改 这个按键，我试了一下直接设置 `inoremap <C-i> <ESC>` 就生效了，你的配置是怎么写的呢？

我也直接试了一下 `inoremap <C-i> <ESC>`，发现还是不生效，然后试下 `inoremap <C-y> <ESC>` 是生效的。

```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur
```

现在的版本是这个，我升级到最新试试。

**Comment by towry** [comment]
@Avimitin 升级到最新版本后好了，应该是 neovim 的问题。

我升级的最新版本：

```
NVIM v0.8.0-dev+415-gdd8b6094c
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by Avimitin** [comment]
> oops
> 
> 是工作了，但是tab键不工作了，现在 tab 键会退出 insert mode。看来不能用 `<C-i>`了。

可以尝试把 tab 键弄回 tab，重新把它 map 成他自己
