### ISSUE TITLE
Separate Tab and Buffer

### ISSUE THREAD

**Issue by Avimitin** [Avimitin/nvim#52]
In current implementation, tabs and buffer are always mixed together: buffers looks like tab in current UI. I am thinking about if we let tab to be tab, let buffer to be buffer, and add a new buffer switch plugin, the UI might be better.

**Comment by Avimitin** [comment]
No, this is bad idea.

**Comment by towry** [comment]
https://github.com/mrjones2014/legendary.nvim

不知道这个插件你有没有看过，感觉用来管理keymap很不错，不用记的那么多的keymap，只需要记得几个description里面的关键字就行了。

**Comment by Avimitin** [comment]
有试过，但是要把所有键位重新绑定一次，我就懒得搞了。
