### ISSUE TITLE
Unexpected Error: "attempt to index local 'selection' (a nil value)"

### ISSUE THREAD

**Issue by towry** [Avimitin/nvim#54]
```
/plugins/enhance/keymap.lua:83: attempt to index local 'selection' (a nil value)
stack traceback:
        /Users/xxxx/.config/nvim/lua/plugins/enhance/keymap.lua:83: in function 'run_replace_or_original'
        ...k/packer/opt/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...ack/packer/opt/telescope.nvim/lua/telescope/mappings.lua:341: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
```

Steps to reproduce:

1. use `<leader>s` to open the telescope search mode.
2. input some random string like `abcdefg`. (not choose any pre-defined items)
3. press `enter` key.

**Comment by Avimitin** [comment]
Fixed, please pull from the master branch.

**Comment by towry** [comment]
谢谢。BTY，你可以给这个仓库加个 sponsor 按钮 ~

**Comment by Avimitin** [comment]
Sponsor 要有美国 ASN 和银行卡，开不了

**Comment by towry** [comment]
@Avimitin 我突然发现 https://github.com/Avimitin/nvim/blob/master/lua/plugins/enhance/keymap.lua#L12 这个 `<leader>t` 不管用了，以为是什么其他程序影响的，然后发现手动运行 `:NvimTreeToggle<cr>` 也不行，很奇怪，不知道你有没有这个问题。
`:NvimTreeOpen` 是OK 的。

**Comment by Avimitin** [comment]
> @Avimitin 我突然发现 [`master`/lua/plugins/enhance/keymap.lua#L12](https://github.com/Avimitin/nvim/blob/master/lua/plugins/enhance/keymap.lua?rgh-link-date=2022-11-29T06%3A22%3A53Z#L12) 这个 `<leader>t` 不管用了，以为是什么其他程序影响的，然后发现手动运行 `:NvimTreeToggle<cr>` 也不行，很奇怪，不知道你有没有这个问题。 `:NvimTreeOpen` 是OK 的。

我这边没有任何问题，你的配置文件在哪？建议开个新的 issue 来讨论。
