### ISSUE TITLE
Strange/incorrect snippet autocomplete

### ISSUE THREAD

**Issue by towry** [Avimitin/nvim#56]
This is a bit annoying,  for example:

<img width="325" alt="截屏2022-11-29 23 26 34" src="https://user-images.githubusercontent.com/8279858/204571716-55a22d7a-66bd-4319-85c2-0ea15068d46d.png">

This is useless and incorrect, sometimes it will shows autocomplete like  `try {` , and i accidentally trigger it and a bunch code like
 
```js
try {
} catch (err) {
}
```

generated.

<img width="315" alt="截屏2022-11-29 23 34 16" src="https://user-images.githubusercontent.com/8279858/204572927-3fd57272-bb6a-4c3f-8143-238de0fb53b5.png">

In the above case, if I press tab key to indent, it will trigger the completion unintended.

* filetype: vue/javascript
* forked repo: https://github.com/pze/nvim

**Comment by Avimitin** [comment]
I found it annoying too, maybe I should remove those snippets from https://github.com/rafamadriz/friendly-snippets and only use user-defined ver. Let me think about it.

**Comment by Avimitin** [comment]
Removed in https://github.com/Avimitin/nvim/commit/8feb2ea58331c33aa83e2088490a9350b95f3f8e. Since this commit, every snippet needs to be hand written by user.
