### ISSUE TITLE
latest commits break up fresh new setup

### ISSUE THREAD

**Issue by towry** [Avimitin/nvim#57]
```
nstalling packer to /Users/towry/.local/share/nvim/site/pack/packer/opt/packer.nvim
Error executing vim.schedule lua callback: /Users/towry/.config/nvim/lua/plugins/enhance/keymap.lua:146: module 'hydra' not found:
```

I was trying to reproduce another issue with fresh new repo, and encounter this error.

_Originally posted by @towry in https://github.com/Avimitin/nvim/issues/41#issuecomment-1331743451_

**Comment by Avimitin** [comment]
I make some mistake on the plugin load sequences. I need to rewrite the whole load process. Please wait.

**Comment by Avimitin** [comment]
It's currently fix by `pcall` to workaround. But I don't think this is an elegant way. I want to rewrite the whole configuration but it is a huge code base needs to be changed. So it will need more time to finish.
