### ISSUE TITLE
A bit hard to get coc.nvim to work in this setup ..

### ISSUE THREAD

**Issue by towry** [Avimitin/nvim#58]
I am trying to get coc.nvim works in this nvim setup, and I have disabled nvim-cmp in `vue` ft and enable coc.nvim only in `vue` ft,

The reason to do this is because vue support in neovim is very poor, so I want to use coc.nvim in where `nvim-cmp` doesn't works well.

See:
- [coc config](https://github.com/pze/nvim/blob/master/lua/plugins/coding/config/coc_config.lua#L10)
- [disable nvim cmp in vue](https://github.com/pze/nvim/blob/master/lua/plugins/completion/config.lua#L54)
- [enable coc in vue](https://github.com/pze/nvim/blob/master/lua/plugins/coding/repos_diy.lua#L24)

## **The issue:**

I followed the official coc doc and setup keymap for using `<tab>` as navigation key, but error happened,

```
Error detected while processing function coc#pum#_navigate[4]..<SNR>98_select
_by_index[2]..<SNR>98_set_cursor[21]..<SNR>98_select_line[8]..coc#dialog#plac
e_sign:                                                                      
line    3:                                                                   
E155: Unknown sign: CocCurrentLine
```

No useful search result on google, asked on coc-cn gitter, author said that "你用 sign undefine 把 sign 清除了把" which i do not understand and i am sure i didn't do that.

A bit help would be much appreciated.

**Comment by Avimitin** [comment]
What does "vue support in neovim is very poor" mean? Doesn't it provide a LSP?

I only use coc.nvim since neovim 0.4.0, so I need to understand how it works now, to solve your problem.

**Comment by towry** [comment]
I may have some misunderstanding of of neovim native lsp works. I will look into it further.
Thanks.

**Comment by Avimitin** [comment]
Maybe a vuels is enough? https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#vuels. Then if you are using my configuration, just add `{"vue", "vuels"}` into `lua/custom.lua` should be enough.

**Comment by towry** [comment]
终于搞定了，体验完美

https://github.com/pze/nvim/pull/3/files

**Comment by Avimitin** [comment]
> 终于搞定了，体验完美。
> 
> [pze/nvim#3 (files)](https://github.com/pze/nvim/pull/3/files)
> 
> neovim lsp + volar language server + mason

Maybe you can just install the volar lsp yourself and then add a single `{ "vue", "volar"}` like this https://github.com/Avimitin/nvim/blob/master/lua/custom.example.lua#L48.
