### ISSUE TITLE
null-ls setup not work properly

### ISSUE THREAD

**Issue by towry** [Avimitin/nvim#61]
https://github.com/Avimitin/nvim/blob/master/lua/plugins/coding/config/init.lua#L57

I believe we should use `null_ls_settings.null_ls.enable_eslint` in the following reference instead of just `null_ls_settings.enable_eslint`.

After I tweak it in my local setup, the null-ls works in the vue file.

But the code action triggered every time i move the cursor, i don't know if this is normal, because it seems is the first time i get null-ls working in vue file(or other files other than lua ...).

<img width="316" alt="截屏2022-12-03 14 39 36" src="https://user-images.githubusercontent.com/8279858/205428355-96315545-51cf-4b7f-8451-6e086bc56de6.png">

**Comment by Avimitin** [comment]
Oh, I finally know why my stylus doesn't work :(

**Comment by towry** [comment]
试了下js，看了log，有正常的 eslint 输出，比如某个变量未定义。但是并没有在 noevim 这里提示出来，估计配置还有问题。

**Comment by Avimitin** [comment]
我研究一下，我之前一直以为是正常工作了。
