### ISSUE TITLE
Fix obsolete command: preview_definition

### ISSUE THREAD

**Issue by towry** [Avimitin/nvim#66]
https://github.com/Avimitin/nvim/blob/258ee0d1d3a05d9d597641da15e393baa078b040/lua/overlays/rc/lspconfig_keymap.lua#L36

This seems not working anymore and it give deprecation information, should use `Lspsaga peek_definition` instead.

Also, what dose this [command](https://github.com/Avimitin/nvim/blob/258ee0d1d3a05d9d597641da15e393baa078b040/lua/overlays/rc/lspconfig_keymap.lua#L47) do? :
```lua
vim.lsp.buf.declaration
```

It is not working in any files (lua, ts) ...

![截屏2022-12-07 14 06 35](https://user-images.githubusercontent.com/8279858/206102312-b567e692-c871-4ae2-b503-8a7fe020164d.png)

I thought it is used to jump to the declaration like what VSCode does.

**Comment by Avimitin** [comment]
declaration is an standard protocol in LSP, but most of the server doesn't implement it. Maybe I should just remove them, since Rust doesn't implemented it too.

**Comment by Avimitin** [comment]
I've left some more friendly hint in notification. So the second issue might considered fixed?

**Comment by towry** [comment]
Yes, thanks.
