### ISSUE TITLE
nvim-cmp auto selecting makes line break not possible

### ISSUE THREAD

**Issue by towry** [Avimitin/nvim#67]
I don't know is this `nvim-cmp` issue or the config issue.

https://user-images.githubusercontent.com/8279858/206616777-ca6a56cc-baa6-4e8c-ab15-4093ec178c83.mov

You can see, after I input "," next to the string, nvim-cmp popup and auto select the first item, which is strange and makes it hard to enter new line.

"nameName" comes from this implementation: extractCodeName.ts
```ts
export default function extractCodeName(
  vm: { code?: string | number; name?: string | number },
  codeName: string,
  nameName: string
) {
  if (!vm) {
    vm = {};
  }

  return {
    [codeName]: vm.code,
    [nameName]: vm.name,
  };
}

```

forked: https://github.com/pze/nvim

lsp info:
![截屏2022-12-09 11 43 54](https://user-images.githubusercontent.com/8279858/206619442-0578b21a-d46a-41c9-81dd-225b8dbbf9e9.png)

**Comment by Avimitin** [comment]
Maybe I should remove the auto selection. Let  me digging out how Intellij IDEA do this stuff.

**Comment by towry** [comment]
Issue still exist.

**Comment by Avimitin** [comment]
This should now be fixed.

**Comment by towry** [comment]
> This should now be fixed.

Yes, thanks.

![截屏2022-12-09 15 29 57](https://user-images.githubusercontent.com/8279858/206648724-3b023917-f8b4-43e2-b23b-fb1e39f16a05.png)

👍
