### ISSUE TITLE
lsp diagnostics not updating (LSP & null-ls)

### ISSUE THREAD

**Issue by towry** [Avimitin/nvim#68]
Sometimes, after a while editing a typescript files, the typescript/eslint error messages doesn't go away, even though I have fixed the error.

The root cause of this issue maybe due to the conflict of null-ls diagnostic and LSP.

The null-ls eslint diagnostic source is enabled here:
https://github.com/Avimitin/nvim/blob/56b31c7f45d0331170255ac5c02c8c757d9292f1/lua/overlays/rc/null_ls.lua#L12

Some search results:

- [Fix for diagnostics not updating issue](https://www.reddit.com/r/neovim/comments/p0tube/fix_for_diagnostics_not_updating_issue/)
- [LSP Diagnostics sometimes not being cleared ](https://github.com/neovim/neovim/issues/17017#issuecomment-1009481135)

I will keep searching for a solution.

**Comment by Avimitin** [comment]
This is annoying... I don't write React for a long time so I don't know what's happening. I will digging it out this weekend.

**Comment by towry** [comment]
This prove that the issue comes from the conflict of null-ls and lsp.
<img width="1260" alt="截屏2022-12-10 23 27 37" src="https://user-images.githubusercontent.com/8279858/206862658-0b080452-2c6f-431a-baa8-2c00ecc10923.png">

There are to incorrect error reporting:

1. comes from lsp, `FRIEND_REQUEST_ID` is used in the below code, but it is reporting declared but not used.
2. The yellow line is reported by eslint, we can see it seems is not synced the buffer with null-ls, I have fixed `FRIEND_REQUEST_I` to `FRIEND_REQUEST_ID`.

I have done 'save' action and insert-leave action.

**Comment by towry** [comment]
More debug info update.

I have set `update_in_insert = false` in lspconfig. and `update_in_insert = false` in null-ls config.

https://github.com/Avimitin/nvim/blob/56b31c7f45d0331170255ac5c02c8c757d9292f1/lua/overlays/rc/lspconfig.lua#L68

The `null-ls` works in expect, but lspconfig with volar doesn't.

So, in editing file, after trigger an error like `var abc is defined but not used`, and i trigger a save without leaving insert-mode(custom keymap ctrl-s), the lspconfig immediately cleared the ts errors. but null-ls doesn't. If I press <esc> to leave the insert-mode, the null-ls will update the diagnostics.
