### ISSUE TITLE
Weird Scrolling

### ISSUE THREAD

**Issue by ricbermo** [Avimitin/nvim#7]
Hey, how you doing?

I'm trying out your config and I'm seeing this weird scrolling. It's happening when I press the arrow keys (up, down) see how the status-bar is almost at the top.

Thanks

![image](https://user-images.githubusercontent.com/2601363/148691243-8f9f6dd1-f0cc-4485-9d60-318afb5c0bee.png)

**Comment by Avimitin** [comment]
This is because I set the arrow key to windows resize. Please use hjkl as navigate key. Or you can delete the arrow key map in lua/key map.lua file.

**Comment by Avimitin** [comment]
I've updated the arrow key functionality. It's now set as a windows navigate key. You can see details in this commit. https://github.com/Avimitin/nvim/commit/70576e9da25ad02fe0ce6ef11a4f2da0eb614e60
