### ISSUE TITLE
statusline in splits

### ISSUE THREAD

**Issue by towry** [Avimitin/nvim#70]
<img width="714" alt="截屏2022-12-11 17 52 52" src="https://user-images.githubusercontent.com/8279858/206897055-5b7ec147-f269-4815-835a-cee69e292f7c.png">

I am using the 'gruvbox' theme, if you have splits in vertical layout, you can see the statusline is transparent, make it like there is no split ...

Don't know if this is theme-specific issue.

**Comment by Avimitin** [comment]
Yes it's the theme design. I want it to look like bubble. But apparently it decrease readability on my side too. I will add some background color in next update.

**Comment by Avimitin** [comment]
But I still feels the line-like statusline is not as pretty as bubble-like..

**Comment by towry** [comment]
TBH, personally not in favor of this style statusline ... 
I don't look at it very often/almost not, so I think more simple the better.
