### ISSUE TITLE
Next step

### ISSUE THREAD

**Issue by Avimitin** [Avimitin/nvim#71]
> Sort by priority

~~- [ ] write a guidance for starter~~
~~- [ ] replace vim-vsnip with its successor LuaSnip~~

**Comment by xcfw** [comment]
Huge thanks for a great job on config! I love it so much!
1. Could you consider making it easier to configure which plugins need to be loaded always or move settings for conditional load to the top level (custom.lua or init.lua), loading gitsigns+fugitive+flog when nvim is opened is something I can't fix myself. 
2. Also it would be nice to have **all** keymaps in init.lua or custom.lua, including plugin related ones so it's easier to adopt and change if necessary and it will bring more order to config.
3. Same goes to plugin repo's, one place to rule them all is the most straightforward and easy to adopt way of managing them.
Sorry if I misunderstood concept and use your config in a wrong way.

**Comment by Avimitin** [comment]
- [ ] Replace packer with lazy.nvim (For lockfile support)
- [ ] Replace "setup in init.lua" init mechanism with injection (For gitignore and project local settings)
- [ ] Merge plugins key mapping/configuration
- [ ] Split lspconfig setup by filetype (Rust/Scala are setup by their corresponding plugin, also deno doesn't use eslint, we need more specific control.)
