### ISSUE TITLE
tailwindcss doesn't support jump to implementation

### ISSUE THREAD

**Issue by towry** [Avimitin/nvim#75]
![截屏2022-12-15 15 32 09](https://user-images.githubusercontent.com/8279858/207800250-651b1540-ff34-43d3-8008-4bcb64994a96.png)

I suppose multiple lsp is allowed for same filetype, because it does in vscode.

I have setup tsserver, tailwindcss for typescriptreact file, but it seems current keybinding is not working very well with two lsp servers.

**Comment by Avimitin** [comment]
I got COVID this day, so I can't help you now. I can't even get up.

**Comment by towry** [comment]
Sorry to hear about that, get well soon.
