### ISSUE TITLE
什麼是"翻斗花园"?

### ISSUE THREAD

**Issue by nyngwang** [Avimitin/nvim#77]
Just curious about the term.

**Comment by Avimitin** [comment]
This is a combination of multiple Chinese meme. “翻斗花园” is a fake address came from an old Chinese anime [《大耳朵图图》](https://en.wikipedia.org/wiki/Big_Ear_Tutu) . The main character "图图" lives in "翻斗大街翻斗花园2号楼1001". It is really hard to explain this meme XD.

**Comment by nyngwang** [comment]
OK, I got it! Thanks for your explanation! (I don't know why but this term is like a bee buzzing around in my head when I first saw it. Very good repo btw!)
