### ISSUE TITLE
notworking with neovim installed from snapd

### ISSUE THREAD

**Issue by kyzsuukii** [Avimitin/nvim#78]
am try to use this awesome configuration

but when clone and run nvim its doest work

![Screenshot_20230816-020024_Termux.png](https://github.com/Avimitin/nvim/assets/110718021/d9d4e8ca-0c26-4ef7-b905-367843e9b31f)

![Screenshot_20230816-020028_Termux.png](https://github.com/Avimitin/nvim/assets/110718021/c9873b1c-b4e9-44d0-ad3c-522237fa4275)

**Comment by Avimitin** [comment]
Um, there are some incomplete work in master branch. Please checkout to this commit https://github.com/Avimitin/nvim/commit/60667f7c31624dce31274b83ad565196f4bb25bd

```bash
git checkout 60667f7c31624dce31274b83ad565196f4bb25bd
```

**Comment by kyzsuukii** [comment]
> Um, there are some incomplete work in master branch. Please checkout to this commit https://github.com/Avimitin/nvim/commit/60667f7c31624dce31274b83ad565196f4bb25bd
> 
> ```bash
> git checkout 60667f7c31624dce31274b83ad565196f4bb25bd
> ```

![Screenshot_20230816-105329_Termux.png](https://github.com/Avimitin/nvim/assets/110718021/5dfcc187-12ab-49b3-9b95-8ad6ef122191)

**Comment by kyzsuukii** [comment]
> Um, there are some incomplete work in master branch. Please checkout to this commit https://github.com/Avimitin/nvim/commit/60667f7c31624dce31274b83ad565196f4bb25bd
> 
> ```bash
> git checkout 60667f7c31624dce31274b83ad565196f4bb25bd
> ```

ahh forgot clone again but when try

`git checkout 60667f7c31624dce31274b83ad565196f4bb25bd`

still same

![Screenshot_20230816-105644_Termux.png](https://github.com/Avimitin/nvim/assets/110718021/c489a45b-5d58-42ff-8936-972d1f462e23)

![Screenshot_20230816-105632_Termux.png](https://github.com/Avimitin/nvim/assets/110718021/01ca2f53-c407-41ff-b152-e419981d2ad4)

**Comment by Avimitin** [comment]
I've abandoned all the trash commits. Please clone the master branch again, it should work out of the box now.

**Comment by kyzsuukii** [comment]
![Screenshot_20230816-220933_Termux.png](https://github.com/Avimitin/nvim/assets/110718021/78c23dd8-9297-45f9-ad12-71c0bcf25db6)

nice

**Comment by kyzsuukii** [comment]
![Screenshot_20230816-221443_Termux.png](https://github.com/Avimitin/nvim/assets/110718021/87051057-e183-4559-aef2-fec2378d9781)

![Screenshot_20230816-221449_Termux.png](https://github.com/Avimitin/nvim/assets/110718021/c806a812-9dc5-4051-9d37-cff473643591)

but i got another issue

**Comment by Avimitin** [comment]
That's because you are not using the latest neovim. You can try to update to unstable version.

**Comment by Avimitin** [comment]
If snapd doesn't ship latest neovim, you can try to use th is commit https://github.com/Avimitin/nvim/commit/8a8ce397094afb1898de9678d9a01e2ac9ecf5fb.
